Update azure-pipelines-pr.yaml

diff --git a/pipelines/azure-pipelines-pr.yaml b/pipelines/azure-pipelines-pr.yaml
--- a/pipelines/azure-pipelines-pr.yaml
+++ b/pipelines/azure-pipelines-pr.yaml
@@ -12,12 +12,12 @@ variables:
   - name: TERRAFORM_SEC_VERSION
     value: "v1.26.0"
   - name: GITHUB_REPO
-    value: "Think-Cube/terraform-azure-resource-group"
+    value: "Think-Cube/Think-Cube-terraform-azure-resource-group-test"
   - group: GITHUB-PAT-TOKEN
   - name: VM_IMAGE
     value: ubuntu-latest
   - name: MODULE_NAME
-    value: "terraform-azure-resource-group"
+    value: "terraform-azure-resource-group"    
 pool:
   vmImage: $(VM_IMAGE)
 stages:
@@ -52,26 +52,29 @@ stages:
             chmod +x /tmp/terraform-docs
           displayName: 'Download terraform-docs' 
         - script: |
+            # Variables
+            github_token="$(GITHUB_TOKEN)" 
             # Generate or update README.md
             /tmp/terraform-docs markdown table . > README.md
 
-            # Check for changes in README.md
-            if git diff --name-only | grep -q README.md; then
-              echo "README.md file updated. Preparing to commit changes."
-              git config --global user.email "devops-bot@example.com"
+            # Check if README.md has been updated or created and add to PR
+            if [ -f README.md ]; then
+              echo "README.md file generated/updated."
+              git config --global user.email "devops-bot@thinkcube.dev"
               git config --global user.name "DevOps Bot"
               git add README.md
               git commit -m "Update README.md with module documentation"
-
+              
               # Set remote URL with authentication token
-              git remote set-url origin https://$(GITHUB_TOKEN)@github.com/Think-Cube/terraform-azure-resource-group.git
+              git remote set-url origin https://$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO).git
 
               # Pull the latest changes to avoid conflicts (source branch of the PR)
-              git pull origin '$(System.PullRequest.SourceBranch)' --rebase || exit 1
+              git pull origin $(System.PullRequest.SourceBranch) --rebase
 
               # Push changes
-              git push origin HEAD:'$(System.PullRequest.SourceBranch)' || exit 1
+              git push origin HEAD:$(System.PullRequest.SourceBranch)
             else
-              echo "No changes in README.md detected."
+              echo "Failed to generate README.md"
+              exit 1
             fi
           displayName: 'Generate and Update README.md Documentation'
